version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: online-order-management-pg
    environment:
      POSTGRES_USER: oom_user_LQkR
      POSTGRES_PASSWORD: r9VYUDHXxRk
      POSTGRES_DB: oom_db
    ports:
      - "5432:5432"
    volumes:
      - online-order-management-pg-data:/var/lib/postgresql/data

volumes:
  online-order-management-pg-data:
