version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: online-order-management-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - online-order-management-pg-data:/var/lib/postgresql/data

volumes:
  online-order-management-pg-data:
